import type { Metadata } from "next";
import Image from "next/image";
import PageIntro from "@/components/PageIntro";
import Reveal from "@/components/Reveal";
import WorkGrid from "@/components/WorkGrid";
export const metadata: Metadata = { title: "Work", description: "Selected records, music videos, and real studio sessions from Miiir.", alternates: {canonical:"/work"} };
export default function WorkPage() {
  return <><PageIntro number="02" eyebrow="RECORDS & SESSIONS" title="Behind the records" description="Hear the work. See the sessions. Straight from the Bay." /><section id="videos" className="shell work-page-videos"><WorkGrid embed /></section><section className="section shell"><Reveal><div className="section-heading"><div><p className="eyebrow">IN THE ROOM</p><h2 className="section-title">The sessions<span>.</span></h2></div><a href="https://www.instagram.com/stillmiiir/p/Daok7veGtiD/" target="_blank" rel="noopener noreferrer" className="text-link">Original post ↗</a></div></Reveal><div className="session-gallery">{[{id:"01",caption:"Studio nights",alt:"Two artists working at a laptop in a studio"},{id:"03",caption:"Around the desk",alt:"Artists gathered around the computer during a studio session"},{id:"02",caption:"Between sessions",alt:"People gathered with cars inside a warehouse"}].map((photo,index)=><Reveal key={photo.id} delay={index*70}><figure><div className="gallery-photo"><Image unoptimized src={`/media/session-${photo.id}-original.jpg`} alt={photo.alt} fill sizes="(max-width: 700px) 100vw, 33vw" className="object-cover" /></div><figcaption><span>0{index+1} / {photo.caption}</span><span>↗</span></figcaption></figure></Reveal>)}</div><p className="source-credit">Photos from <a href="https://www.instagram.com/stillmiiir/p/Daok7veGtiD/" target="_blank" rel="noopener noreferrer">@stillmiiir’s studio carousel</a>. First photo tags <a href="https://www.instagram.com/shotbyrogelio/" target="_blank" rel="noopener noreferrer">@shotbyrogelio</a>.</p></section><section className="shell contact-strip"><Reveal><p className="eyebrow">WHAT’S NEXT?</p><a className="big-contact" href="/contact">LET’S MAKE<br />A RECORD <span>↗</span></a></Reveal></section></>;
}
